### ISSUE TITLE
pip-compile doesn't work with pip 20.1

### ISSUE THREAD

**Issue by frankmijn** [open-zaak/open-zaak#585]
**Describe the bug**
When generating base.txt using 

`pip-compile --no-index requirements/base.in 
`

The  following error is returned:

AttributeError: 'ParsedRequirement' object has no attribute 'editable'

When using pip version 20.0.2 (`pip install pip==20.0.2`) everything works as expected. 

**To Reproduce**
1. Run `pip-compile --no-index requirements/base.in` in the base folder with pip version 20.1 installed.

**Expected behavior**
base.txt containing all the requirements.

**Comment by jaishah** [comment]
I am facing the same issue while trying to generate the requirements.txt using pip 20.1.
Before upgrading pip it was working as expected. any workaround for this ?

**Comment by joeribekker** [comment]
This has to do the release of a new `pip` version.

Unfortunately, `pip` is one of those dependencies that are outside the scope of *requirements files* and is installation/user specific and therefore not pinned.

`pip` version 20.x is not supported by our pinned version of `pip-tools` (4.4.0) and causes an error. In version 5.x of `pip-tools`, [this is resolved](https://github.com/jazzband/pip-tools/blob/master/CHANGELOG.md#500-2020-04-16).

The short-term workaround is to simply update `pip-tools`, using:

```
python -m pip install -U pip-tools
```

The solution it to update `pip-tools` in the requirement files for which I'll make a PR.
