### PR TITLE
Fixes #585 - Updated pip tools and set minimum pip version.

### LINKED ISSUE #585: pip-compile doesn't work with pip 20.1
**Describe the bug**
When generating base.txt using 

`pip-compile --no-index requirements/base.in 
`

The  following error is returned:

AttributeError: 'ParsedRequirement' object has no attribute 'editable'

When using pip version 20.0.2 (`pip install pip==20.0.2`) everything works as expected. 

**To Reproduce**
1. Run `pip-compile --no-index requirements/base.in` in the base folder with pip version 20.1 installed.

**Expected behavior**
base.txt containing all the requirements.

### PR DESCRIPTION
**Pull request by joeribekker**
Fixes #585

**Changes**

Updated `pip-tools` to 5.2.1. This will require `pip>=20.0`.

NOTE: Apologies for the changed format of requirements. This is caused by the new pip tools version.

### CODE REVIEW

**Comment by sergei-maertens** [comment]
@joeribekker I triggered the Travis build again, hope it reports back correctly now. Github has been having some availability issues recently.

**Comment by sergei-maertens** [comment]
Thanks to Steven's patch from yesterday and rebasing on that, flake8 now also passes. Merging.
